// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int nTimes = Integer.parseInt(args[0]);
	int lowerNumber = 0;
	int higherNumber = 0;
	for (int count = 0; count < nTimes; count++) {
		double randomNumber = Math.random();
		if (randomNumber < 0.5) {
			lowerNumber++;
		} else {
			higherNumber++;
		}
	}
	if (higherNumber == 0) {
		System.out.println("> 0.5: " + lowerNumber + " times");
		System.out.println("<= 0.5: " + higherNumber + " times");
	} else {
		double ratio = (double) lowerNumber / higherNumber;
		System.out.println("> 0.5: " + lowerNumber + " times");
		System.out.println("<= 0.5: " + higherNumber + " times");
		System.out.println("Ratio: " + ratio);
	}
	}
}
